<section id="section-about" class="section-about">
  <img src="<?= $baseUrl ?>/img/ProfilePic.jpg" alt="Photo de Romain">
  <p>Bonjour, je m'appelle Romain, je suis ingénieur actuellement à la recherche d'un nouveau défi dans le développement et l’intégration Web !</p>
  <p>Je travaille actuellement en tant que chargé d’affaires en maintenance de centrales solaires à Montpellier. Mais ces dernières années, je n’ai plus l’impression d’évoluer techniquement, et le coté créatif me manque énormément. Parallèlement à ça, depuis le lycée je suis très attiré par l’informatique et la programmation (je me souviens encore de mon premier programme de calcul de régression linéaire sur TI82 !), et dès qu’une occasion se présentait, c’était avec grand plaisir que je codais quelques lignes. Finalement cette évidence m'a enfin sauté aux yeux : pourquoi ne pas faire de cette passion mon métier ?!</p>
  <p>C’est pourquoi j’ai décidé de suivre une formation intensive pour devenir développeur et intégrateur web à la <a href="https://3wa.fr/"  target="_blank">3W Academy</a>. Cette formation a pour but d’apporter aux élèves le maximum de connaissances en un minimum de temps, c’est pourquoi plus de 90 % du temps est consacré à la pratique. J’ai ainsi appris à maîtriser les 5 piliers principaux pour développer un site ou une application web :</p>
  <p><strong>HTML, CSS, JavaScript, PHP, MySQL</strong></p>
  <p>J’ai également appris à utiliser des librairies extrêmement utiles telles que jQuery, ainsi que le framework Symfony. Avant de commencer la formation, je connaissais déjà bien Wordpress que j'utilisais pour <a href="https://bisonvoyageur.com/"  target="_blank">un blog personnel</a>, mais maintenant je sais créer des thèmes pour ce CMS.</p>
  <p>Je recherche donc maintenant un poste idéalement polyvalent et enrichissant, dans une équipe dynamique.</p>
  <a href="<?= $baseUrl ?>/docs/CV-Romain_Sire.pdf" class="btn" download>Télécharger mon CV</a>
</section>


