
<form class="login-form" action="<?= $baseUrl ?>/login.php" method="post">
  <h2>Se connecter</h2>
  <p>
    <label for="login">login</label>
    <input type="login" id="login" name="login" placeholder="Nom d'utilisateur" required autofocus>
  </p>
  <p>
    <label for="password">Mot de Passe</label>
    <input type="password" id="password" name="password" placeholder="Mot de passe" required>
  </p>
  <button type="submit" class="btn">S'identifier</button>
</form>