<section id="section-skills" class="section-skills">
    <div class="section-skills-web">
      <h3>Métier du Web</h3>

      <h4>5 piliers :</h4>
      <ul class="section-skills-sans-legende">
        <li><img src="<?= $baseUrl ?>/img/skills/html.svg" alt="HTML"></li>
        <li><img src="<?= $baseUrl ?>/img/skills/css.svg" alt="CSS"></li>
        <li><img src="<?= $baseUrl ?>/img/skills/javascript.svg" alt="JavaScript"></li>
        <li><img src="<?= $baseUrl ?>/img/skills/php.svg" alt="PHP"></li>
        <li><img src="<?= $baseUrl ?>/img/skills/mysql.svg" alt="MySQL"></li>
      </ul>

      <h4>Concepts :</h4>
      <ul class="section-skills-avec-legende">
        <li>
          <img src="<?= $baseUrl ?>/img/skills/oop.svg" alt="POO">
          <p>Programmation Orientée Objet</p>
        </li>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/mvc.svg" alt="MVC">
          <p>Modèle Vue<br>
            Contrôleur</p>
        </li>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/ajax.svg" alt="AJAX">
          <p>JavaScript et XML asynchrones</p>
        </li>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/api.svg" alt="API">
          <p>API : Interface de programmation applicative</p>
        </li>
      </ul>

      <div class="section-skills-web-wrapper">
        <div>
          <h4>Librairies :</h4>
          <ul class="section-skills-sans-legende">
            <li><img src="<?= $baseUrl ?>/img/skills/jquery.svg" alt="jQuery"></li>
            <li><img src="<?= $baseUrl ?>/img/skills/bootstrap.svg" alt="Bootstrap"></li>
          </ul>
        </div>

        <div>
          <h4>Framework :</h4>
          <ul class="section-skills-avec-legende">
            <li>
              <img src="<?= $baseUrl ?>/img/skills/symfony.svg" alt="Symfony">
              <p>Symfony</p>
            </li>
          </ul>
        </div>

        <div>
          <h4>CMS :</h4>
          <ul class="section-skills-avec-legende">
            <li>
              <img src="<?= $baseUrl ?>/img/skills/wordpress.svg" alt="WordPress">
              <p>WordPress</p>
            </li>
          </ul>
        </div>
      </div>

    </div>

    <div class="section-skills-cross section-skills-avec-legende">
      <h3>Compétences transversales</h3>
      <ul>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/gantt.svg" alt="Gestion de projet">
          <p>Gestion de projets<br>(GANTT)</p>
        </li>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/moe.svg" alt="Maitrise d'oeuvre">
          <p>Maîtrise d'oeuvre<br>(Budget 400 k€)</p>
        </li>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/research.svg" alt="R&D">
          <p>R&D et Publications Scientifiques</p>
        </li>
        <li>
          <img src="<?= $baseUrl ?>/img/skills/customer.svg" alt="Relation clients">
          <p>Relation Clients<br>(devis, facturation)</p>
        </li>
      </ul>
    </div>

    <div class="section-skills-lang section-skills-avec-legende">
      <h3>Langues</h3>
      <ul>
        <li>
          <p>Français</p>
          <img src="<?= $baseUrl ?>/img/skills/french.svg" alt="Langue natale">
        </li>
        <li>
          <p>Anglais</p>
          <img src="<?= $baseUrl ?>/img/skills/english.svg" alt="Niveau avancé">
        </li>
        <li>
          <p>Espagnol</p>
          <img src="<?= $baseUrl ?>/img/skills/spanish.svg" alt="Niveau moyen">
        </li>
      </ul>
    </div>
</section>